const RAIL_X_LEFT = 170
const RAIL_X_RIGHT = 1050
const RAIL_X_LEFT_OFFSET = 23
const RAIL_X_RIGHT_OFFSET = 13
const RAIL_WIDTH = RAIL_X_RIGHT - RAIL_X_LEFT

const CANVAS_WIDTH = 1200
const CANVAS_HEIGHT = 500

export { RAIL_X_RIGHT, RAIL_X_LEFT, RAIL_WIDTH, CANVAS_WIDTH, CANVAS_HEIGHT, RAIL_X_LEFT_OFFSET, RAIL_X_RIGHT_OFFSET }

