import { GameObject } from "../types.ts";

export enum GameObjectId {
  BASE = 'BASE',
  GENERATOR_POWER = 'GENERATOR_POWER',
  FREQUENCY_MODE = 'FREQUENCY_MODE',
  VPP_MODE = 'VPP_MODE',
  SINE_MODE = 'SINE_MODE',
  OUTPUT_BTN = 'OUTPUT_BTN',
  GENERATOR_NUMPAD_1 = 'GENERATOR_NUMPAD_1',
  GENERATOR_NUMPAD_2 = 'GENERATOR_NUMPAD_2',
  GENERATOR_NUMPAD_3 = 'GENERATOR_NUMPAD_3',
  GENERATOR_NUMPAD_4 = 'GENERATOR_NUMPAD_4',
  GENERATOR_NUMPAD_5 = 'GENERATOR_NUMPAD_5',
  GENERATOR_NUMPAD_6 = 'GENERATOR_NUMPAD_6',
  GENERATOR_NUMPAD_7 = 'GENERATOR_NUMPAD_7',
  GENERATOR_NUMPAD_8 = 'GENERATOR_NUMPAD_8',
  GENERATOR_NUMPAD_9 = 'GENERATOR_NUMPAD_9',
  GENERATOR_NUMPAD_0 = 'GENERATOR_NUMPAD_0',
  GENERATOR_NUMPAD_DOT = 'GENERATOR_NUMPAD_DOT',
  GENERATOR_NUMPAD_BACKSPACE = 'GENERATOR_NUMPAD_BACKSPACE',
  GENERATOR_DATA = 'GENERATOR_DATA',
  OSCILOGRAPG_POWER = 'OSCILOGRAPG_POWER',
  ACQUIRE_BTN = 'ACQUIRE_BTN',
  POSITION_CONTROL_LEFT = 'POSITION_CONTROL_LEFT',
  POSITION_CONTROL_RIGHT = 'POSITION_CONTROL_RIGHT',
  SCALE_CONTROL_LEFT = 'SCALE_CONTROL_LEFT',
  SCALE_CONTROL_RIGHT = 'SCALE_CONTROL_RIGHT',
  OSCILOGRAPH_DATA = 'OSCILOGRAPH_DATA',
}

export type Lab307GameObject = GameObject<GameObjectId>

export type GeneratorInputMode = 'frequency' | 'vpp' | null

export type GeneratorOutputMode = 'sine' | 'square' | 'ramp' | 'pulse' | 'noise' | 'arb' | null
